  version: "1.0"
  services:
    app:
      image: aakron_api
      env_file:
        - .env
      environment:
        RAILS_ENV: development
      ports:
        - 3000:3000
    # db:
    #   image: postgres:alpine3.15
    #   environment:
    #     POSTGRES_PASSWORD: example